/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

/* Table schema:
CREATE TABLE kv_store_52cdd920 (
  key TEXT NOT NULL PRIMARY KEY,
  value JSONB NOT NULL
);
*/

// View at https://supabase.com/dashboard/project/qsslpkxyhcevqqcuwwrc/database/tables

// This file provides a simple key-value interface for storing Figma Make data. It should be adequate for most small-scale use cases.
// src/lib/supabase.ts
/* src/lib/supabase.ts */
// kv_store.ts
import { createClient } from "@supabase/supabase-js";

// Node environment variables
const SUPABASE_URL = process.env.VITE_SUPABASE_URL!;
const SUPABASE_ANON_KEY = process.env.VITE_SUPABASE_ANON_KEY!;

// Supabase client
const supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY);

// Set a key-value pair
export const set = async (key: string, value: any): Promise<void> => {
  const { error } = await supabase
    .from("kv_store_52cdd920")
    .upsert({ key, value });
  if (error) throw new Error(error.message);
};

// Get a key-value pair
export const get = async (key: string): Promise<any> => {
  const { data, error } = await supabase
    .from("kv_store_52cdd920")
    .select("value")
    .eq("key", key)
    .maybeSingle();
  if (error) throw new Error(error.message);
  return data?.value;
};

// Delete a key
export const del = async (key: string): Promise<void> => {
  const { error } = await supabase
    .from("kv_store_52cdd920")
    .delete()
    .eq("key", key);
  if (error) throw new Error(error.message);
};

// Multi-set
export const mset = async (keys: string[], values: any[]): Promise<void> => {
  const { error } = await supabase
    .from("kv_store_52cdd920")
    .upsert(keys.map((k, i) => ({ key: k, value: values[i] })));
  if (error) throw new Error(error.message);
};

// Multi-get
export const mget = async (keys: string[]): Promise<any[]> => {
  const { data, error } = await supabase
    .from("kv_store_52cdd920")
    .select("value")
    .in("key", keys);
  if (error) throw new Error(error.message);
  return data?.map((d) => d.value) ?? [];
};

// Multi-delete
export const mdel = async (keys: string[]): Promise<void> => {
  const { error } = await supabase
    .from("kv_store_52cdd920")
    .delete()
    .in("key", keys);
  if (error) throw new Error(error.message);
};

// Search by prefix
export const getByPrefix = async (prefix: string): Promise<any[]> => {
  const { data, error } = await supabase
    .from("kv_store_52cdd920")
    .select("key, value")
    .like("key", prefix + "%");
  if (error) throw new Error(error.message);
  return data?.map((d) => d.value) ?? [];
};
