/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "qsslpkxyhcevqqcuwwrc";
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFzc2xwa3h5aGNldnFxY3V3d3JjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIyMDUwMjQsImV4cCI6MjA3Nzc4MTAyNH0.6RWFWeX3kyyP44Qa7XfoxMxjQbHKViLw4UkDrFgfZMg";